-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "shop" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "isOnline" BOOLEAN NOT NULL DEFAULT false,
    "scope" TEXT,
    "expires" DATETIME,
    "accessToken" TEXT NOT NULL,
    "userId" BIGINT,
    "firstName" TEXT,
    "lastName" TEXT,
    "email" TEXT,
    "accountOwner" BOOLEAN NOT NULL DEFAULT false,
    "locale" TEXT,
    "collaborator" BOOLEAN DEFAULT false,
    "emailVerified" BOOLEAN DEFAULT false
);

-- CreateTable
CREATE TABLE "Settings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "isEnabled" BOOLEAN NOT NULL DEFAULT false,
    "fontChosen" TEXT NOT NULL DEFAULT 'Default',
    "fontsizeValue" INTEGER NOT NULL DEFAULT 16,
    "textTitleFieldValue" TEXT,
    "contentValue" TEXT,
    "canBeClosed" BOOLEAN NOT NULL DEFAULT false,
    "countdown" BOOLEAN NOT NULL DEFAULT false,
    "showCoupon" BOOLEAN NOT NULL DEFAULT false,
    "showButton" BOOLEAN NOT NULL DEFAULT false,
    "collectLeads" BOOLEAN NOT NULL DEFAULT false,
    "expiryDate" BOOLEAN NOT NULL DEFAULT false,
    "expiryDateValue" TEXT,
    "widthChoice" BOOLEAN NOT NULL DEFAULT false,
    "heightChoice" BOOLEAN NOT NULL DEFAULT false,
    "paddingChoice" BOOLEAN NOT NULL DEFAULT false,
    "marginChoice" BOOLEAN NOT NULL DEFAULT false,
    "daysValue" INTEGER,
    "hoursValue" INTEGER,
    "minutesValue" INTEGER,
    "secondsValue" INTEGER,
    "couponValue" TEXT,
    "textButtonFieldValue" TEXT,
    "urlButtonFieldValue" TEXT,
    "leadChosen" TEXT NOT NULL DEFAULT 'Collect All',
    "positionChosen" TEXT NOT NULL DEFAULT 'Top',
    "styleChosen" TEXT NOT NULL DEFAULT 'Full Width Bar',
    "bgColor" TEXT NOT NULL DEFAULT '{}',
    "pColor" TEXT NOT NULL DEFAULT '{}',
    "sColor" TEXT NOT NULL DEFAULT '{}',
    "deviceChosen" TEXT NOT NULL DEFAULT 'Both',
    "btnEffectChosen" TEXT NOT NULL DEFAULT 'None',
    "afterBtnClickChosen" TEXT NOT NULL DEFAULT 'Nothing',
    "triggerChosen" TEXT NOT NULL DEFAULT 'None',
    "topPaddingValue" INTEGER,
    "bottomPaddingValue" INTEGER,
    "leftPaddingValue" INTEGER,
    "rightPaddingValue" INTEGER,
    "topMarginValue" INTEGER,
    "bottomMarginValue" INTEGER,
    "leftMarginValue" INTEGER,
    "rightMarginValue" INTEGER,
    "widthPixelValue" INTEGER,
    "heightPixelValue" INTEGER
);
